/*
 * snes_main.c - M1.4: boot the SNES, put a level on screen, and let the real
 * Famidash physics drive the player.
 *
 * main() runs the actual cube_movement() and x_movement() from SAUCE/ against
 * the real collision map. Nothing here reimplements gameplay; it only supplies
 * the hardware the game expects.
 */

#include <stdint.h>

/* --- SNES registers ----------------------------------------------------- */
#define REG(a) (*(volatile uint8_t *)(a))
#define INIDISP  REG(0x2100)
#define OBSEL    REG(0x2101)
#define OAMADDL  REG(0x2102)
#define OAMDATA  REG(0x2104)
#define BGMODE   REG(0x2105)
#define BG1SC    REG(0x2107)
#define BG12NBA  REG(0x210B)
#define BG1HOFS  REG(0x210D)
#define BG1VOFS  REG(0x210E)
#define VMAIN    REG(0x2115)
#define VMADDL   REG(0x2116)
#define VMADDH   REG(0x2117)
#define VMDATAL  REG(0x2118)
#define VMDATAH  REG(0x2119)
#define CGADD    REG(0x2121)
#define CGDATA   REG(0x2122)
#define TM       REG(0x212C)
#define TS       REG(0x212D)
#define NMITIMEN REG(0x4200)
#define RDNMI    REG(0x4210)
#define MDMAEN   REG(0x420B)
#define MEMSEL   REG(0x420D)

#define VRAM_TILES  0x0000
#define VRAM_BG1MAP 0x1000
#define VRAM_OBJ    0x2000

/* --- assets, generated by tools/snes_m0.py ------------------------------ */
extern const uint8_t bg1_tiles[];       /* 4096 bytes, SNES 2bpp   */
extern const uint8_t bg1_tilemap[];     /* 2048 bytes, 32x32 words */
extern const uint8_t bg1_cgram[];       /*   32 bytes, 16 colours  */
extern const uint8_t level_collmap[];   /* 1024 bytes, 4 rooms     */

/* --- game globals (famidash.h defines these; see shim_core.c) ----------- */
extern uint8_t collMap[4][256];
extern uint16_t currplayer_x, currplayer_y;
extern int16_t currplayer_vel_y;
extern uint8_t currplayer_mini, currplayer_gravity, gamemode, framerate;
extern uint8_t jumps, currplayer_table_idx;
extern uint16_t scroll_x, scroll_y;

/*
 * The player hitbox. The collision probes offset from Generic.y by
 * Generic.height to find the player's feet, so leaving it zero makes every
 * probe test the wrong row and the player never lands. On the NES this is
 * filled in by sprite_loading.h, which is not part of this build yet.
 */
struct Base {
    uint8_t x, y, width, height;
};
extern struct Base Generic;
extern const uint8_t CUBE_WIDTH[];
extern const uint8_t CUBE_HEIGHT[];

void cube_movement(void);
void x_movement(void);
void update_currplayer_table_idx(void);
uint8_t pad_poll(uint8_t pad);

/* --- helpers ------------------------------------------------------------ */
static void vram_upload(uint16_t word_addr, const uint8_t *src, uint16_t len)
{
    uint16_t i;
    VMAIN = 0x80;                       /* +1 word, increment on high byte */
    VMADDL = (uint8_t)word_addr;
    VMADDH = (uint8_t)(word_addr >> 8);
    for (i = 0; i < len; i += 2) {
        VMDATAL = src[i];
        VMDATAH = src[i + 1];
    }
}

static void cgram_upload(const uint8_t *src, uint16_t len)
{
    uint16_t i;
    CGADD = 0;
    for (i = 0; i < len; i++)
        CGDATA = src[i];
}

/* One 8x8 white square for the player, built at runtime so no art is needed. */
static void make_player_tile(void)
{
    uint8_t i;
    VMAIN = 0x80;
    VMADDL = (uint8_t)VRAM_OBJ;
    VMADDH = (uint8_t)(VRAM_OBJ >> 8);
    /* 4bpp: planes 0/1 solid (colour 3), planes 2/3 clear -> palette index 3 */
    for (i = 0; i < 8; i++) { VMDATAL = 0xFF; VMDATAH = 0xFF; }
    for (i = 0; i < 8; i++) { VMDATAL = 0x00; VMDATAH = 0x00; }
}

/*
 * OAM is 544 bytes: a 512-byte low table (4 bytes per sprite) followed by a
 * 32-byte high table (2 bits per sprite: X bit 9 and size). Clearing only the
 * low table leaves the high table full of power-on garbage, which shows up as
 * stray sprites scattered over the screen.
 */
static void oam_clear_all(void)
{
    uint16_t i;
    OAMADDL = 0;
    REG(0x2103) = 0;
    for (i = 0; i < 128; i++) {
        OAMDATA = 0;             /* X    */
        OAMDATA = 240;           /* Y    - below the 224-line display */
        OAMDATA = 0;             /* tile */
        OAMDATA = 0;             /* attr */
    }
    for (i = 0; i < 32; i++)
        OAMDATA = 0;             /* high table: X bit 9 = 0, size = small */
}

static void oam_player(uint8_t x, uint8_t y)
{
    OAMADDL = 0;
    REG(0x2103) = 0;
    OAMDATA = x;                 /* X */
    OAMDATA = y;                 /* Y */
    OAMDATA = 0;                 /* tile 0 of the OBJ base */
    OAMDATA = 0x30;              /* priority 3, palette 0 */
}

/*
 * Poll the vblank flag rather than taking an NMI. snes-HiROM.scm only defines
 * the reset vector; NMI/IRQ point at whatever happens to be in $FFE0-$FFFB, so
 * enabling NMI without installing a handler crashes into garbage. Auto-joypad
 * read works without NMI.
 */
#define HVBJOY_VBLANK 0x80
#define HVBJOY_AUTOJOY 0x01

static void wait_vblank(void)
{
    while (REG(0x4212) & HVBJOY_VBLANK)     /* wait out any vblank in progress */
        ;
    while (!(REG(0x4212) & HVBJOY_VBLANK))  /* then wait for the next one */
        ;
}

/* --- boot --------------------------------------------------------------- */
static void video_init(void)
{
    uint16_t i;

    INIDISP = 0x8F;                     /* forced blank */
    NMITIMEN = 0;
    /* FastROM, matching the full ROM and the header's map mode byte (0x31).
       Both images share shim/src/snes_header.s, so leaving this at 0 would
       leave the small ROM running at 2.68MHz while its header claimed 3.58. */
    MEMSEL = 1;

    for (i = 0x2101; i < 0x2134; i++)
        REG(i) = 0;

    vram_upload(VRAM_TILES, bg1_tiles, 4096);
    vram_upload(VRAM_BG1MAP, bg1_tilemap, 2048);
    cgram_upload(bg1_cgram, 32);
    make_player_tile();
    oam_clear_all();

    /* sprite palette: CGRAM 128.., colour 3 = white */
    CGADD = 128 + 3;
    CGDATA = 0xFF; CGDATA = 0x7F;

    BG1SC = ((VRAM_BG1MAP >> 10) << 2);  /* tilemap base, 32x32 */
    BG12NBA = 0;                         /* BG1 chars at $0000 */
    OBSEL = (VRAM_OBJ >> 13);            /* OBJ base, 8x8/16x16 */
    BGMODE = 0;

    BG1HOFS = 0; BG1HOFS = 0;
    BG1VOFS = 0xFF; BG1VOFS = 0xFF;      /* -1: map row 0 on screen line 0 */

    TM = 0x11;                           /* BG1 + OBJ */
    TS = 0;
    INIDISP = 0x0F;
    NMITIMEN = 0x01;                     /* auto-joypad read only; no NMI handler exists */
}

static void level_init(void)
{
    uint16_t i;
    uint8_t *dst = &collMap[0][0];

    for (i = 0; i < 1024; i++)
        dst[i] = level_collmap[i];

    /* Drop the player in above the floor of room 1, in cube mode. */
    gamemode = 0;                       /* GAMEMODE_CUBE */
    framerate = 1;
    currplayer_mini = 0;
    currplayer_gravity = 0;
    currplayer_x = 0x9000;              /* 8.8 fixed: x = 144, over the block mass */
    currplayer_y = 0x2000;              /* y = 32: starts in the air, falls */
    currplayer_vel_y = 0;
    scroll_x = 0;
    scroll_y = 0;

    /* Cube hitbox, normally set by sprite_loading.h. */
    Generic.width = CUBE_WIDTH[0];      /* 0x0F */
    Generic.height = CUBE_HEIGHT[0];    /* 0x0F */

    update_currplayer_table_idx();
}

int main(void)
{
    video_init();
    level_init();

    for (;;) {
        wait_vblank();
        pad_poll(0);

        /*
         * The real thing: unmodified Famidash cube physics, running against
         * the real collision map. Gravity, jumping (A / Up) and landing all
         * come from SAUCE/gamemodes/gamemode_cube.h.
         *
         * x_movement() is deliberately not called yet. It drives the constant
         * rightward run, and the collision map here is a fixed 16-metatile
         * window, so the player would immediately leave mapped ground and fall
         * forever. Horizontal travel needs the camera plus collision-map
         * streaming - that is the next step, not something to fake here.
         */
        cube_movement();

        oam_player((uint8_t)(currplayer_x >> 8), (uint8_t)(currplayer_y >> 8));
    }
}
