#!/usr/bin/env python3
"""Emit EVERY level of a level set, compressed, plus the tables to decode it.

Replaces the single-level precomputed column stream. That stream cost 230KB of
ROM for one level - 1796 tile columns of 128 bytes - which is why the port has
been stuck on Stereo Madness. The whole level set is 198KB of `.lz`, so decoding
at run time as the NES does is both smaller and general.

The SNES makes this much easier than the NES did: the largest level decompresses
to 19.7KB of RLE stream, and there is 128KB of WRAM, so the whole level can be
decompressed once at load rather than streamed through a window.

Emitted:
    out/level_lz.s / .bin      every level's LZ stream, concatenated
    out/level_spr.s / .bin     every level's sprite-object stream
    out/level_table.c          per-level offsets, headers and names
    out/metatile_words.c       metatile -> four SNES tilemap words

METATILE_WORDS is the expansion table the runtime needs: one metatile is 2x2
tiles and its palette comes from its own attribute byte, so the four tilemap
words are precomputed here rather than assembled on the SNES. 256 metatiles x 4
words = 2KB, against doing three shifts and an or per tile at run time.

    python tools/gen_levels.py [--root C:/famidash] [--lvlset lvlset_A]
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import snes_m0 as m                                     # noqa: E402
import gen_assets                                       # noqa: E402

HEADER_FIELDS = gen_assets.HEADER_FIELDS


def parse_level_order(root: Path, lvlset: str):
    """The level set's own order, from _level_list_lo in all_level_table.s."""
    path = root / "LEVELS/include" / lvlset / "all_level_table.s"
    text = path.read_text(errors="replace")
    m_ = re.search(r"^_level_list_lo:\s*$", text, re.M)
    if not m_:
        sys.exit(f"{path}: _level_list_lo not found")
    names = []
    for line in text[m_.end():].splitlines():
        mm = re.match(r"\s*\.byte\s+\.lobyte\(level_data_(\w+)\)", line)
        if mm:
            names.append(mm.group(1))
        elif line.strip() and not line.strip().startswith(";"):
            break
    return names


def parse_all_headers(root: Path, lvlset: str, names):
    """The 13 header bytes, including the generated per-level music IDs."""
    path = root / "LEVELS/include" / lvlset / "all_level_data.s"
    text = path.read_text(errors="replace")
    defines = gen_assets.parse_header_defines(root, lvlset)
    out = {}
    for n in names:
        mm = re.search(r"^\tlevel_data_%s:\s*$" % re.escape(n), text, re.M)
        if not mm:
            continue
        vals = []
        for line in text[mm.end():].splitlines():
            if ".incbin" in line:
                break
            bm = re.match(r"\s*\.byte\s+([^;]+)", line)
            if bm:
                vals.append(gen_assets.eval_byte(bm.group(1).strip(), defines))
        out[n] = [v if v is not None else 0 for v in vals[:len(HEADER_FIELDS)]]
    return out


def emit_blobs(outdir: Path, stem: str, section: str, blobs, names):
    """One .incbin SECTION PER LEVEL, not one concatenated blob.

    A single section cannot exceed a bank (docs/HANDOFF.md trap 39), and 198KB
    of LZ is three of them. Per-level sections also let the table be a real
    `const uint8_t *const []` - pointers the compiler builds itself, with no
    offset arithmetic and no bank byte to reconstruct by hand (trap 28).

    The LevelData memories in src/snes-HiROM.scm are declared one per bank, so
    the linker cannot split a level across a bank boundary either.
    """
    asm = ["; Generated by tools/gen_levels.py - do not edit.",
           f"; {len(blobs)} streams, one section each.", ""]
    total = 0
    for b, n in zip(blobs, names):
        (outdir / f"{stem}_{n}.bin").write_bytes(b)
        total += len(b)
        asm += [f"        .section {section},text,root",
                f"        .public {stem}_{n}",
                f"{stem}_{n}:",
                f'        .incbin "out/{stem}_{n}.bin"', ""]
    (outdir / f"{stem}.s").write_text("\n".join(asm))
    return total


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default="C:/famidash")
    ap.add_argument("--lvlset", default="lvlset_A")
    ap.add_argument("--outdir", default=str(ROOT / "out"))
    ap.add_argument("--levels", type=int, default=0,
                    help="cap the number of levels (0 = all)")
    args = ap.parse_args()
    root, outdir = Path(args.root), Path(args.outdir)

    names = parse_level_order(root, args.lvlset)
    if args.levels:
        names = names[:args.levels]
    headers = parse_all_headers(root, args.lvlset, names)

    lvldir = root / "LEVELS/include" / args.lvlset / "EXPORTS/level"
    sprdir = root / "LEVELS/include" / args.lvlset / "EXPORTS/sprite"

    kept, lz_blobs, spr_blobs, max_rle = [], [], [], 0
    for n in names:
        lz_path, spr_path = lvldir / f"{n}.lz.bin", sprdir / f"{n}.bin"
        if not lz_path.exists() or n not in headers:
            print(f"    (skipping {n}: no .lz or no header)")
            continue
        lz = lz_path.read_bytes()
        # Decompress here purely to size the runtime buffer - the ROM carries
        # the compressed form.
        max_rle = max(max_rle, len(m.lz_decompress(lz)))
        kept.append(n)
        lz_blobs.append(lz)
        spr_blobs.append(spr_path.read_bytes() if spr_path.exists() else b"\xFF")

    lz_size = emit_blobs(outdir, "level_lz", "lvldata", lz_blobs, kept)
    spr_size = emit_blobs(outdir, "level_spr", "lvldata", spr_blobs, kept)

    def table(name, vals, width=1):
        body = ", ".join(str(v) for v in vals)
        t = "uint8_t" if width == 1 else "uint16_t" if width == 2 else "uint32_t"
        return f"const {t} {name}[{len(vals)}] = {{ {body} }};\n"

    externs = "\n".join(f"extern const uint8_t level_lz_{n}[];\n"
                        f"extern const uint8_t level_spr_{n}[];" for n in kept)
    lz_ptrs = ", ".join(f"level_lz_{n}" for n in kept)
    spr_ptrs = ", ".join(f"level_spr_{n}" for n in kept)
    c = ["/* Generated by tools/gen_levels.py - do not edit. */",
         "#include <stdint.h>", "",
         externs, "",
         f"const uint8_t level_count = {len(kept)};",
         "",
         "/* Real pointer arrays, so the compiler builds the 24-bit addresses",
         " * itself - no offsets to add and no bank byte to reconstruct. */",
         f"const uint8_t *const level_lz_ptr[{len(kept)}] = {{ {lz_ptrs} }};",
         f"const uint8_t *const level_spr_ptr[{len(kept)}] = {{ {spr_ptrs} }};",
         "",
         "/* The 13-byte level header, one array per field: the port reads them",
         " * individually, and separate arrays avoid any struct-layout question. */"]
    for i, field in enumerate(HEADER_FIELDS):
        c.append(table(f"lvl_{field}", [headers[n][i] if i < len(headers[n]) else 0
                                        for n in kept]))
    song_i = HEADER_FIELDS.index("song")
    song_ids = [headers[n][song_i] for n in kept]
    (outdir / "level_song.lua").write_text(
        "-- Generated by tools/gen_levels.py - do not edit.\nreturn { "
        + ", ".join(str(v) for v in song_ids) + " }\n")
    # Names for the level select, fixed width so the menu can index them.
    # 23 is the longest id across the sets (lvlset_HUGE); at MENU_LEFT 6 that
    # ends at column 29, inside the 32-tile line.
    NAME_W = 23
    names_flat = []
    for n in kept:
        s = n.upper()[:NAME_W].ljust(NAME_W)
        names_flat.extend(ord(ch) for ch in s)
    c.append(f"#define LEVEL_NAME_W {NAME_W}")
    c.append(table("level_names", names_flat))
    # What the level select should read back as, for tools/verify_menu.lua. It
    # decodes the tilemap rather than trusting a screenshot, and this keeps the
    # expected text tied to the level set instead of hardcoded in the script.
    (outdir / "menu_expect.txt").write_text(
        "".join(n.upper()[:NAME_W] + "\n" for n in kept))
    (outdir / "level_table.c").write_text("\n".join(c) + "\n")

    # --- metatile -> four tilemap words -------------------------------------
    metatiles = m.parse_metatiles(root / "METATILES" / "metatiles.inc")
    # FOUR tables of 256, not one interleaved table of 1024.
    #
    # build_tile_column reads two of the four words per metatile, and with the
    # interleaved form every read cost a shift and an add to build the index -
    # per metatile, per column, in the hottest loop in the renderer. Split, the
    # metatile byte IS the index and the two reads come from two tables at the
    # same offset.
    # ONE interleaved table of 1024, not four planes of 256.
    #
    # Four planes look better for build_tile_column - the metatile byte is
    # the index, with no shift to build it - and measured SLOWER: 90.3% of
    # 60Hz against 91.6% on the heaviest level. Four far base pointers cost
    # more than the shift they save. Left interleaved deliberately.
    words = []
    for i in range(256):
        mt = metatiles[i] if i < len(metatiles) else metatiles[0]
        pal = mt["pal"]
        words += [m.tilemap_word(mt["tl"], pal), m.tilemap_word(mt["tr"], pal),
                  m.tilemap_word(mt["bl"], pal), m.tilemap_word(mt["br"], pal)]
    (outdir / "metatile_words.c").write_text(
        "/* Generated by tools/gen_levels.py - do not edit.\n"
        " * One metatile is 2x2 tiles; the palette comes from its own\n"
        " * attribute byte, which is what makes this correct despite 47 of\n"
        " * 235 tiles being used under more than one palette. Precomputed as\n"
        " * finished SNES tilemap words so the runtime expansion is a copy. */\n"
        "#include <stdint.h>\n\n"
        + table("metatile_words", words, 2))

    print(f"    level_lz.s   ({len(kept)} levels, {lz_size:,} bytes compressed)")
    print(f"    level_spr.s  ({spr_size:,} bytes of sprite streams)")
    print(f"    level_table.c, metatile_words.c "
          f"(largest level decompresses to {max_rle:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
