#!/usr/bin/env python3
"""Emit out/nes_palette.c - the NES index -> SNES CGRAM lookup used at runtime.

The asset pipeline already converts NES palette indices to CGRAM words when it
builds the level's colours. pal_col() has to do the same conversion at run time,
and if the two ever disagree the sprites and the background drift apart in a way
that is very hard to see. Generating the runtime table from snes_m0.py's own
table is what stops that.

    python tools/gen_palette.py [--outdir out]
"""
import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

from snes_m0 import nes_color_to_cgram   # noqa: E402  single source of truth

# The level header's bg and ground colours also go in one step DARKER, and the
# step is a lookup, not arithmetic: palBrightTable3 in LIB/asm/neslib.s maps $30
# to $10, not to $20. The four 16-byte tables from palBrightTable3 onwards are
# contiguous and the routine indexes it with a full 0..63 colour, so 64 entries
# come from tables 3, 4, 5 and 6.
NESLIB = "LIB/asm/neslib.s"
DARKEN_TABLES = ["palBrightTable3", "palBrightTable4",
                 "palBrightTable5", "palBrightTable6"]


def parse_darken(root: Path):
    import re
    text = (root / NESLIB).read_text(errors="replace")
    out = []
    for name in DARKEN_TABLES:
        m = re.search(r"^%s:\s*$" % re.escape(name), text, re.M)
        if not m:
            sys.exit(f"{NESLIB}: {name} not found")
        # Strip the comment first: palBrightTable6's says "$10 because $20 is
        # the same as $30", which parses as three more table entries.
        line = text[m.end():].lstrip().splitlines()[0].split(";")[0]
        vals = [int(v[1:], 16) for v in re.findall(r"\$[0-9a-fA-F]{2}", line)]
        if len(vals) != 16:
            sys.exit(f"{NESLIB}: {name} has {len(vals)} bytes, expected 16")
        out += vals
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default=str(ROOT / "out"))
    ap.add_argument("--root", default="C:/famidash", help="game repo, read-only")
    args = ap.parse_args()

    words = [nes_color_to_cgram(i) for i in range(64)]
    darken = parse_darken(Path(args.root))

    out = [
        "/* Generated by tools/gen_palette.py - do not edit.",
        " * NES palette index (0..63) -> SNES CGRAM word, using the same table as",
        " * tools/snes_m0.py so the runtime and the baked assets cannot diverge.",
        " */",
        "#include <stdint.h>",
        "",
        "const uint16_t nes_to_cgram[64] = {",
    ]
    for i in range(0, 64, 8):
        row = ", ".join(f"0x{w:04X}" for w in words[i:i + 8])
        out.append(f"    {row},")
    out.append("};")
    out.append("")
    out.append("/* palBrightTable3 in LIB/asm/neslib.s: one brightness step darker. */")
    out.append("const uint8_t nes_darken[64] = {")
    for i in range(0, 64, 8):
        out.append("    " + ", ".join(f"0x{v:02X}" for v in darken[i:i + 8]) + ",")
    out.append("};")

    path = Path(args.outdir) / "nes_palette.c"
    path.write_text("\n".join(out) + "\n")
    print(f"    nes_palette.c (64 entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
