#!/usr/bin/env python3
"""Emit out/instr_ranges.lua - the PC range of each routine worth profiling.

tools/profile_instr.lua and tools/profile_collide.lua register an exec callback
over a routine's whole address range to count the instructions executed inside
it. The ranges come from the linker map, because they move on every build; a
hand-written or stale copy silently profiles whatever now sits at those
addresses, which has already produced one "the routine executes zero
instructions" and one phantom regression (docs/HANDOFF.md traps 5 and 92).

    python tools/gen_instr_ranges.py [--map out/game_full.map]
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# The per-frame routines the frame timeline names, plus the compiler helpers -
# _ValueSwitch16 was 11% of a frame and is invisible unless it is listed.
WANTED = (
    "sprite_collide", "check_spr_objects", "draw_sprites", "drawplayerone",
    "trail_loop", "draw_screen", "oam_meta_spr", "shim_meta_run", "oam_clear",
    "check_collision", "sprite_collide_lookup", "pal_col", "colBrightness",
    "_ValueSwitch16", "_Mul16", "_Div16", "x_movement", "common_gravity_routine",
)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--map", default=str(ROOT / "out" / "game_full.map"))
    ap.add_argument("--out", default=str(ROOT / "out" / "instr_ranges.lua"))
    args = ap.parse_args()

    path = Path(args.map)
    if not path.exists():
        sys.exit(f"{path} not found - build the game ROM first")

    # A function's address is on the line AFTER its name (trap 91).
    found, pending = {}, None
    for line in path.read_text(errors="replace").splitlines():
        m = re.match(r"^([A-Za-z_]\w*) in section '(\S+)'", line)
        if m:
            pending = m.group(1)
            continue
        if pending:
            mm = re.search(r"placed at address ([0-9a-f]{6})-([0-9a-f]{6})", line)
            if mm and pending in WANTED:
                found[pending] = (int(mm.group(1), 16), int(mm.group(2), 16))
            pending = None

    out = ["-- Generated by tools/gen_instr_ranges.py - do not edit.",
           "-- PC ranges for the profiling scripts; they move on every build.",
           "return {"]
    for name, (lo, hi) in sorted(found.items(), key=lambda kv: kv[1][0]):
        out.append(f'  {{ name = "{name}", lo = 0x{lo:06X}, hi = 0x{hi:06X} }},')
    out.append("}")
    Path(args.out).write_text("\n".join(out) + "\n")

    missing = [w for w in WANTED if w not in found]
    print(f"    instr_ranges.lua ({len(found)} routines"
          + (f"; not in this build: {', '.join(missing)}" if missing else "") + ")")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
