#!/usr/bin/env python3
"""Emit out/addrs.lua from the linker map.

WRAM symbol addresses move on every rebuild - anything that adds or removes a
variable reshuffles the 'zfar' section. Trace scripts must never hardcode them;
they `dofile` the table this writes instead.

Addresses are emitted as WRAM offsets (bank $7E stripped) because that is what
emu.memType.snesWorkRam is indexed by.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
import argparse

_ap = argparse.ArgumentParser()
_ap.add_argument("--map", default=str(ROOT / "out" / "game.map"))
_ap.add_argument("--out", default=str(ROOT / "out" / "addrs.lua"))
_args = _ap.parse_args()
MAP = Path(_args.map)
OUT = Path(_args.out)

SYM = re.compile(r"^\s+([A-Za-z_][A-Za-z0-9_]*) = ([0-9a-f]{6})$")

# The map lists file-scope statics ONLY in this form - they get no entry in the
# `name = address` symbol table, because they are not global. Without it a
# script asking for a static reads nil and silently pokes address 0.
#
# There are TWO layouts, and only one of them is on a single line. Variables put
# the address on the same line as the name; functions wrap it onto the next.
# Handling just the one-line form found every static variable and no static
# FUNCTION, so profiling scripts silently skipped the routines they were written
# to measure - they hooked nothing and reported a clean timeline.
NAMED = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*) in section '\S+'(.*)$")
PLACED = re.compile(r"placed at address ([0-9a-f]{6})-")


def main() -> int:
    if not MAP.exists():
        sys.exit(f"{MAP} not found - build the game ROM first")

    syms = {}
    pending = None
    for line in MAP.read_text(errors="replace").splitlines():
        m = SYM.match(line)
        if m:
            syms.setdefault(m.group(1), int(m.group(2), 16))
            pending = None
            continue
        m = NAMED.match(line)
        if m:
            pending = m.group(1)
            rest = PLACED.search(m.group(2))
            if rest:
                syms.setdefault(pending, int(rest.group(1), 16))
                pending = None
            continue
        if pending:
            rest = PLACED.search(line)
            if rest:
                syms.setdefault(pending, int(rest.group(1), 16))
            pending = None

    # $7E for the HiROM build, $40 for the SA-1 one - the SA-1 cannot see WRAM
    # at all, so its state lives in BW-RAM on the cartridge. Both are the same
    # kind of thing to a trace script (an offset into the machine's main data
    # memory), so both are emitted under `wram`; only the emulator memory type
    # differs, snesWorkRam against snesSaveRam.
    base = 0x400000 if any(0x400000 <= a < 0x410000 for a in syms.values())            else 0x7E0000
    wram = {n: a - base for n, a in syms.items() if base <= a < base + 0x10000}
    # Function entry points, for execution hooks. On HiROM the code sits in banks
    # $C0-$C3 and these are full 24-bit CPU addresses, not offsets - that is what
    # emu.addMemoryCallback(cpuExec) wants.
    code = {n: a for n, a in syms.items() if 0xC00000 <= a < 0xC40000}

    with OUT.open("w") as f:
        f.write(f"-- generated by tools/gen_addrs.py from {MAP.name}; do not edit\n")
        f.write("-- values are $7E WRAM offsets, i.e. emu.memType.snesWorkRam indices\n")
        f.write("return {\n")
        for name in sorted(wram):
            f.write(f"  {name} = 0x{wram[name]:04X},\n")
        # Nested so a code symbol can never shadow a variable of the same name.
        f.write("  code = {\n")
        for name in sorted(code):
            f.write(f"    {name} = 0x{code[name]:06X},\n")
        f.write("  },\n")
        f.write("}\n")

    print(f"{OUT.name}: {len(wram)} WRAM symbols, {len(code)} code symbols, "
          f"of {len(syms)} total")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
