#!/usr/bin/env python3
"""Emit the C translation units that carry the converted assets into the ROM.

tools/snes_m0.py writes the converted assets as .bin files. The linker needs
them as object code, so this wraps each one in a `const uint8_t[]` that Calypsi
places in ROM (`--rom-code`).

Generated:
    out/assets.c          bg1_tiles, bg1_tilemap, bg1_cgram, level_collmap
    out/metatiles_coll.c  metatiles_coll

These are consumed by shim/src/snes_main.c and shim/src/shim_core.c, which
declare the same symbols `extern const uint8_t x[]`. Sizes are asserted here
rather than trusted, because a short array would link fine and read as garbage
past the end.

    python tools/gen_assets.py [--outdir out]
"""
import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# (C file, [(symbol, source .bin, expected size)])
UNITS = [
    ("assets.c", [
        ("bg1_tiles",     "bg1.tiles.bin",     4096),
        ("bg1_tilemap",   "bg1.tilemap.bin",   2048),
        ("bg1_cgram",     "bg1.cgram.bin",       32),
        ("level_collmap", "level_collmap.bin", 1024),
        # All 256 tiles of NES pattern table 1, 4bpp: icon, portals, main
        # sprites, decorations. 256 x 32 bytes.
        ("spr_tiles",     "spr.tiles.bin",     8192),
        # The ASCII-indexed menu font; the level tileset has no alphabet.
        ("menu_tiles",    "menu.tiles.bin",    4096),
        # Pixel-identical menu art converted from Famidash's own CHR/RLE
        # nametables by gen_famidash_menus.py.
        ("famidash_menu_bg_tiles", "famidash_menu_bg.tiles.bin", 4096),
        ("famidash_menu_cursor_tiles", "famidash_menu_cursor.tiles.bin", 4096),
        ("famidash_menu_demon_tiles", "famidash_menu_demon.tiles.bin", 1024),
        ("famidash_end_bg_tiles", "famidash_end_bg.tiles.bin", 4096),
        ("famidash_practice_bg_tiles", "famidash_practice_bg.tiles.bin", 4096),
        ("famidash_title_map", "famidash_title.map.bin", 2048),
        ("famidash_levelselect_map", "famidash_levelselect.map.bin", 2048),
        ("famidash_end_map", "famidash_end.map.bin", 2048),
        ("famidash_practice_map", "famidash_practice.map.bin", 2048),
        ("famidash_level_lines", "famidash_level_lines.bin", 5712),
        ("famidash_difficulty", "famidash_difficulty.bin", 168),
        ("famidash_stars", "famidash_stars.bin", 168),
        ("famidash_menu_colors", "famidash_menu_colors.bin", 9),
    ]),
    ("metatiles_coll.c", [
        ("metatiles_coll", "metatiles_coll.bin", 256),
    ]),
]

# Emitted separately because its size depends on the level, so it cannot be
# size-asserted like the fixed-shape assets above.
COLL_COLUMNS = ("level_coll_columns", "level_collcols.bin")
COLL_REC_BYTES = 60          # 4 collision pages x 15 rows, per metatile column

# The level's sprite-object stream: 5 bytes per object (x_lo, x_hi, y_lo, y_hi,
# id), terminated by 0xFF in the first byte. load_next_sprite() in nesdash.s
# walks it with a cursor. This is the data behind every coin, orb, pad and
# portal in the level - without it the level cannot be completed.
SPRITE_DATA = "LEVELS/include/{lvlset}/EXPORTS/sprite/{level}.bin"

HEADER = """/* Generated by tools/gen_assets.py - do not edit.
 * Source: {sources}
 */
#include <stdint.h>
"""

# The per-level lengths update_level_completeness() divides by. They are level
# data, generated per level set, and live only in an assembler table - so they
# are parsed out of it rather than duplicated by hand.
LVLSET = "lvlset_A"                     # overridden by --lvlset
LEVEL_TABLE = "LEVELS/include/{lvlset}/all_level_table.s"
LEVEL_DATA = "LEVELS/include/{lvlset}/all_level_data.s"

# The 13-byte level header that precedes the LZ stream in all_level_data.s.
# nesdash.s reads it at level load; the .lz file this port consumes is the RLE
# stream ONLY, so without this the game gets a spawn position of 0 and the
# player starts at the top of the level.
HEADER_FIELDS = [
    "sprite_data_lo", "sprite_data_hi", "sprite_data_bank",
    "song", "gamemode_speed",
    "spawn_y_hi",           # spawn_y_pos = this << 8
    "spawn_scroll_y_lo",    # spawn_scroll_y_pos = 0x0200 | this (high byte is
                            # hardcoded to $02 in nesdash.s - "no levels need
                            # this setting, at least yet")
    "platformer_parallax", "fallspeed_deco", "spike_block",
    "bg_color", "ground_color", "height",
]


def parse_level_header(root, level):
    """The 13 header bytes for one level, from all_level_data.s.

    Values are assembler expressions.  Resolve both the graphics constants and
    the generated music IDs: unlike the three original sprite-pointer bytes,
    every remaining header field is consumed by the SNES port.
    """
    import re
    path = root / LEVEL_DATA.format(lvlset=LVLSET)
    if not path.exists():
        return None
    text = path.read_text(errors="replace")
    m = re.search(r"^	level_data_%s:\s*$" % re.escape(level), text, re.M)
    if not m:
        return None
    defines = parse_header_defines(root)
    out = []
    for line in text[m.end():].splitlines():
        if ".incbin" in line:
            break
        bm = re.match(r"\s*\.byte\s+([^;]+)", line)
        if not bm:
            continue
        out.append(eval_byte(bm.group(1).strip(), defines))
    return out[:len(HEADER_FIELDS)] if out else None


SPACE_DEFINES = "SAUCE/defines/space_defines.h"
MUSIC_DEFINES = "MUSIC/EXPORTS/{lvlset}/musicDefines.h"


def parse_numeric_defines(path):
    """{name: value} for the plain integer #defines in one header."""
    import re
    out = {}
    if not path.exists():
        return out
    for line in path.read_text(errors="replace").splitlines():
        m = re.match(r"\s*#define\s+([A-Za-z_]\w*)\s+"
                     r"(0x[0-9A-Fa-f]+|\d+)\s*(?://.*)?$", line)
        if m:
            out[m.group(1)] = int(m.group(2), 0)
    return out


def parse_header_defines(root, lvlset=None):
    """Constants used by the exported level headers.

    The level headers are written in terms of these - `(1 << 7) | _DECO1`, or
    `song_stereo_madness`.  Graphics symbols have a leading underscore because
    that is how cc65 exports C names to the assembler; music symbols do not.
    Dropping unresolved music symbols to zero made every SNES level play song
    zero even though all 132 original exports were present in ROM.
    """
    out = parse_numeric_defines(root / SPACE_DEFINES)
    out.update(parse_numeric_defines(
        root / MUSIC_DEFINES.format(lvlset=lvlset or LVLSET)))
    return out


def eval_byte(expr, defines=None):
    """Evaluate a header expression; None if it still is not numeric."""
    import re
    e = expr.strip().rstrip(";").strip()
    e = re.sub(r"\$([0-9A-Fa-f]+)", lambda m: str(int(m.group(1), 16)), e)
    if defines:
        # `_DECO1` in the assembler is `DECO1` in space_defines.h.
        def replace_symbol(match):
            name = match.group(0)
            lookup = name[1:] if name.startswith("_") else name
            return str(defines[lookup]) if lookup in defines else name
        e = re.sub(r"\b_?[A-Za-z]\w*\b", replace_symbol, e)
    if not re.fullmatch(r"[0-9()<>|&+\-*\s]+", e):
        return None
    try:
        return int(eval(e, {"__builtins__": {}}, {})) & 0xFF
    except Exception:
        return None
LEVEL_TABLE_RE = r"^_(level_lengths_(?:lo|md|hi)):\s*$"
BYTE_RE = r"^\s*\.byte\s+\.(lo|hi|bank)byte\(\$([0-9A-Fa-f]+)\)"


def parse_level_lengths(root: Path):
    """{symbol: [bytes]} from the level set's assembler table."""
    import re
    path = root / LEVEL_TABLE.format(lvlset=LVLSET)
    if not path.exists():
        return {}
    out, cur = {}, None
    for line in path.read_text(errors="replace").splitlines():
        m = re.match(LEVEL_TABLE_RE, line)
        if m:
            cur = m.group(1)
            out[cur] = []
            continue
        if cur is None:
            continue
        m = re.match(BYTE_RE, line)
        if m:
            value = int(m.group(2), 16)
            shift = {"lo": 0, "hi": 8, "bank": 16}[m.group(1)]
            out[cur].append((value >> shift) & 0xFF)
        elif line.strip() and not line.strip().startswith(";"):
            cur = None          # left the table
    return {k: v for k, v in out.items() if v}


def emit_array(name, data):
    out = [f"\nconst uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        row = ", ".join(f"0x{b:02X}" for b in data[i:i + 16])
        out.append(f"    {row},")
    out.append("};\n")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default=str(ROOT / "out"))
    ap.add_argument("--root", default="C:/famidash",
                    help="game repo, read-only")
    ap.add_argument("--level", default="stereomadness")
    ap.add_argument("--lvlset", default="lvlset_A",
                    help="which level set the length table comes from")
    args = ap.parse_args()
    outdir = Path(args.outdir)
    global LVLSET
    LVLSET = args.lvlset

    for cfile, arrays in UNITS:
        parts, sources = [], []
        for name, binfile, size in arrays:
            path = outdir / binfile
            if not path.exists():
                sys.exit(f"{path} not found - run tools/snes_m0.py first")
            data = path.read_bytes()
            if len(data) != size:
                sys.exit(f"{binfile}: expected {size} bytes, got {len(data)}")
            parts.append(emit_array(name, data))
            sources.append(binfile)

        text = HEADER.format(sources=", ".join(sources)) + "".join(parts)
        (outdir / cfile).write_text(text)
        print(f"    {cfile} ({', '.join(n for n, _, _ in arrays)})")

    name, binfile = COLL_COLUMNS
    path = outdir / binfile
    if not path.exists():
        sys.exit(f"{path} not found - run tools/snes_m0.py first")
    data = path.read_bytes()
    if len(data) % COLL_REC_BYTES:
        sys.exit(f"{binfile}: {len(data)} bytes is not a whole number of "
                 f"{COLL_REC_BYTES}-byte columns")
    text = HEADER.format(sources=binfile) + emit_array(name, data)
    text += f"\nconst uint16_t level_coll_column_count = {len(data) // COLL_REC_BYTES};\n"
    (outdir / "level_collcols.c").write_text(text)
    print(f"    level_collcols.c ({name}, {len(data) // COLL_REC_BYTES} columns)")

    lengths = parse_level_lengths(Path(args.root))
    if not lengths:
        sys.exit(f"{LEVEL_TABLE.format(lvlset=LVLSET)}: level length tables not found under {args.root}")
    text = HEADER.format(sources=LEVEL_TABLE.format(lvlset=LVLSET))
    for name in sorted(lengths):
        text += emit_array(name, lengths[name])
    (outdir / "level_lengths.c").write_text(text)
    print(f"    level_lengths.c ({', '.join(sorted(lengths))}; "
          f"{len(next(iter(lengths.values())))} levels)")

    spr_path = Path(args.root) / SPRITE_DATA.format(lvlset=LVLSET, level=args.level)
    if not spr_path.exists():
        sys.exit(f"{spr_path} not found")
    spr = spr_path.read_bytes()
    text = HEADER.format(sources=str(spr_path.name)) + emit_array("level_sprite_data", spr)
    (outdir / "level_sprites.c").write_text(text)
    print(f"    level_sprites.c (level_sprite_data, {len(spr)} bytes = "
          f"{(len(spr) - 1) // 5} objects)")

    hdr = parse_level_header(Path(args.root), args.level)
    if hdr is None:
        sys.exit(f"{LEVEL_DATA.format(lvlset=LVLSET)}: no header for level {args.level!r}")
    lines = [HEADER.format(sources=f"{LEVEL_DATA.format(lvlset=LVLSET)} (level_data_{args.level})"), ""]
    for field, value in zip(HEADER_FIELDS, hdr):
        note = "" if value is not None else "   /* symbolic, unused here */"
        lines.append(f"const uint8_t lvlhdr_{field} = 0x{(value or 0):02X};{note}")
    (outdir / "level_header.c").write_text("\n".join(lines) + "\n")
    named = {f: v for f, v in zip(HEADER_FIELDS, hdr)}
    print(f"    level_header.c ({args.level}: spawn_y=0x{named['spawn_y_hi']:02X}00, "
          f"spawn_scroll_y=0x02{named['spawn_scroll_y_lo']:02X}, "
          f"height={named['height']})")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
