#!/usr/bin/env python3
"""Emit the physics tables as a Lua oracle, straight from the game's header.

An independent oracle, in the sense of docs/HANDOFF.md trap 61: it is parsed out
of SAUCE/defines/physics_table_defines.cmp.h, not recomputed from whatever the
shim believes. A check that shares its source with the thing under test cannot
fail for the reason you want it to.

The tables are stored split into low and high byte planes and are SIGNED 16-bit;
entry `i` is indexed by currplayer_table_idx = framerate<<2 | mini<<1 | gravity,
which is why consecutive entries are the same magnitude with opposite signs.

    python tools/gen_physics_expect.py --root C:/famidash --outdir out
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFS = "SAUCE/defines/physics_table_defines.cmp.h"

# Only what a check exists for so far. Adding a table here is enough to make it
# available to the Lua side.
WANTED = [
    "SHIP_GRAVITY_BASE", "SHIP_GRAVITY", "SHIP_GRAVITY_AFTER_HOLD",
    "SHIP_GRAVITY_HOLD_FALL",
]


def parse_plane(text, name, plane):
    m = re.search(r"const uint8_t %s_%s\[\]\s*=\s*\{([^}]*)\}" % (re.escape(name), plane),
                  text)
    if not m:
        sys.exit(f"{DEFS}: {name}_{plane} not found")
    return [int(v, 0) for v in re.findall(r"0x[0-9A-Fa-f]+|\d+", m.group(1))]


# CUBE_SPEED is stored differently again: a uint16_t array whose values are
# written ALREADY BYTE-SWAPPED, because the game reads it with ind16BE_load_NOC -
# a big-endian read of the little-endian bytes. So the constant 0xC402 in the
# source is the value 0x02C4 at run time.
def parse_cube_speed(text):
    out = {}
    for fr, name in ((0, "CUBE_SPEED_50"), (1, "CUBE_SPEED_60")):
        m = re.search(r"const uint16_t %s\[\]\s*=\s*\{([^}]*)\}" % name, text)
        if not m:
            sys.exit(f"{DEFS}: {name} not found")
        vals = [int(v, 0) for v in re.findall(r"0x[0-9A-Fa-f]+|\d+", m.group(1))]
        out[fr] = [((v & 0xFF) << 8) | (v >> 8) for v in vals]
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default="C:/famidash")
    ap.add_argument("--outdir", default=str(ROOT / "out"))
    args = ap.parse_args()

    text = (Path(args.root) / DEFS).read_text(errors="replace")
    out = ["-- Generated by tools/gen_physics_expect.py - do not edit.",
           "-- Signed 16-bit, indexed by currplayer_table_idx (0..7).",
           "return {"]
    for name in WANTED:
        lo = parse_plane(text, name, "lo")
        hi = parse_plane(text, name, "hi")
        if len(lo) != len(hi):
            sys.exit(f"{name}: {len(lo)} lo bytes, {len(hi)} hi bytes")
        vals = []
        for l, h in zip(lo, hi):
            v = l | (h << 8)
            vals.append(v - 0x10000 if v >= 0x8000 else v)
        out.append(f"  {name} = {{ " + ", ".join(str(v) for v in vals) + " },")
    speeds = parse_cube_speed(text)
    out.append("  -- Horizontal speed, by [framerate][speed]. Byte-swapped in")
    out.append("  -- the source because the game reads it big-endian.")
    out.append("  CUBE_SPEED = {")
    for fr in (0, 1):
        out.append(f"    [{fr}] = {{ " + ", ".join(str(v) for v in speeds[fr]) + " },")
    out.append("  },")
    out.append("}")
    (Path(args.outdir) / "physics_expect.lua").write_text("\n".join(out) + "\n")
    print(f"    physics_expect.lua ({len(WANTED)} tables)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
