#!/usr/bin/env python3
"""Emit the precomputed tilemap column stream for the ROM.

tools/snes_m0.py already turns the level into fixed-size column records: one
record is 32 tilemap words (64 bytes), which is exactly one VRAM column write.
This repacks them into 64KB bank-sized parts and wraps each in an assembler
`.incbin` - far quicker to build than 128KB of C array initialisers, and the
same bytes.

One part per bank, on purpose:

  - the linker allocates ROM in 64KB bank chunks, so a single 128KB section
    cannot be placed at all;
  - a 64-byte record divides 64KB exactly, so a record never straddles a bank.
    That keeps pointer arithmetic simple now and lets the column write become a
    DMA later - DMA increments the A-bus address within a bank and does not
    carry into the bank byte.

    python tools/gen_columns.py [--outdir out]

READ THIS BEFORE SCALING IT UP. Precomputing the whole level costs 128KB of ROM
for one level. This level set has 46 levels and there are 454 level files across
all sets, so this does not generalise - the full game needs the RLE/metatile
decode to happen at run time, as it does on the NES. This is the single-level
path, deliberately. See docs/M2_LEVEL_RENDER.md.
"""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REC_BYTES = 128                         # 64 tilemap words (64x64 map)
BANK_BYTES = 0x10000
COLS_PER_BANK = BANK_BYTES // REC_BYTES  # 512
MAX_PARTS = 4                            # banks $C4-$C7 in src/snes-HiROM.scm


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default=str(ROOT / "out"))
    args = ap.parse_args()
    outdir = Path(args.outdir)

    # The 64-row stream, not the 32-row one the assembly scroll ROM uses.
    meta_path = outdir / "level.columns64.meta"
    if not meta_path.exists():
        raise SystemExit(f"{meta_path} not found - run tools/snes_m0.py first")
    meta = {}
    for line in meta_path.read_text().splitlines():
        if line.strip():
            k, v = line.split()
            meta[k] = int(v)

    blob = bytearray()
    for i in range(meta["banks"]):
        part = outdir / f"level.cols64.{i}.bin"
        if not part.exists():
            raise SystemExit(f"{part} not found - run tools/snes_m0.py first")
        blob += part.read_bytes()

    n_cols = meta["columns"]
    if n_cols * REC_BYTES > len(blob):
        raise SystemExit(f"stream is {len(blob)} bytes, too short for {n_cols} columns")

    height = meta.get("level_height", 27)
    row_start = meta.get("row_start", 0)
    origin = (60 - 3 - height) * 16 + row_start * 8

    n_parts = (n_cols + COLS_PER_BANK - 1) // COLS_PER_BANK
    if n_parts > MAX_PARTS:
        raise SystemExit(f"{n_cols} columns needs {n_parts} banks; "
                         f"src/snes-HiROM.scm only provides {MAX_PARTS}")

    asm = ["; Generated by tools/gen_columns.py - do not edit.",
           f"; {n_cols} columns of {REC_BYTES} bytes (32 tilemap words), "
           f"{n_parts} bank-sized part(s).", ""]
    for p in range(n_parts):
        chunk = blob[p * BANK_BYTES:(p + 1) * BANK_BYTES]
        chunk += bytes(BANK_BYTES - len(chunk))     # pad to a whole bank
        (outdir / f"level_columns{p}.bin").write_bytes(chunk)
        asm += [f"        .section lvlcols{p},text,root",
                f"        .public level_columns{p}",
                f"level_columns{p}:",
                f'        .incbin "out/level_columns{p}.bin"', ""]
    (outdir / "level_columns.s").write_text("\n".join(asm))

    banks = ", ".join(f"level_columns{p}" for p in range(n_parts))
    externs = "\n".join(f"extern const uint8_t level_columns{p}[];"
                        for p in range(n_parts))
    (outdir / "level_columns_meta.c").write_text(f"""\
/* Generated by tools/gen_columns.py - do not edit. */
#include <stdint.h>

{externs}

const uint16_t level_columns_count = {n_cols};
const uint16_t level_columns_per_bank = {COLS_PER_BANK};

/* Pixel offset from the collision map's origin to the top of the tilemap.
 * The level is bottom-aligned in the 60-metatile-row collision window, so a
 * height-h level starts at metatile row 60 - 3 - h; set_scroll_y() subtracts
 * this so BG1VOFS is relative to the tilemap rather than to the collision
 * space. Without it the camera sits 480px below the level. */
const uint16_t level_scroll_origin = {origin};

/* Column n lives at level_column_banks[n / per_bank][(n %% per_bank) * 64]. */
const uint8_t * const level_column_banks[{n_parts}] = {{ {banks} }};
""")
    print(f"    level_columns.s ({n_cols} columns, {n_parts} bank part(s), "
          f"scroll origin {origin}px)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
