#!/usr/bin/env python3
"""Emit the switchable sprite CHR banks, converted for SNES OBJ.

The NES swaps sprite art with the mapper: `mmc3_set_2kb_chr_bank_0` picks the
player's icon or gamemode art and `_1` picks the level decorations, both in 2KB
units at NES $1000-$17FF and $1800-$1FFF. The SNES has no CHR ROM, so a bank
switch has to become a DMA of converted tiles into OBJ VRAM - which needs the
converted tiles in ROM to begin with. That is what this makes.

One 2KB NES bank is 128 tiles; widened to 4bpp that is 4KB of SNES data, and it
lands at OBJ tiles 256-383 (bank 0) or 384-511 (bank 1).

WHICH BANKS. Only the ones gameplay can reach in this build:

  18, 20, 22, 24, 26     gamemode art (normal and retro)
  28, 30, 32, 34, 36, 38 the decoration banks, `current_deco_type` and +2
  40                     icon 0
  92, 94                 ninja/triangle and football

The other thirteen icon banks (42-66) and the nine contest icons need the
customise menu, which is not ported - `icon` cannot change, so they would be
dead weight. Pass --icons to include more.

Emitted as an assembler file of `.incbin`s rather than C arrays: 56KB of C
initialisers is slow to compile and produces the same bytes (the same reason
tools/gen_columns.py does it that way).

    python tools/gen_sprchr.py [--root C:/famidash] [--outdir out]
"""
import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import snes_m0 as m                                     # noqa: E402

# GAMECHR, exactly as LIB/asm/crt0.s lays it out for level set A. The numbers in
# the comments there are 1KB bank numbers, and this reproduces them: a bank is
# ROM offset N*1024, which snes_m0.verify_chr_banks_against_rom proves against
# the shipped NES ROM.
G = "GRAPHICS/"
GAMECHR = [
    (0,  G + "Level Tiles/SpikesA.chr"),
    (2,  G + "Level Tiles/SpikesB.chr"),
    (4,  G + "Level Tiles/SpikesC.chr"),
    (6,  G + "Level Tiles/BlocksA.chr"),
    (8,  G + "Level Tiles/BlocksB.chr"),
    (10, G + "Level Tiles/BlocksC.chr"),
    (12, G + "Level Tiles/BlocksD.chr"),
    (14, G + "Level Tiles/SawbladesA.chr"),
    (16, G + "Level Tiles/slopesA.chr"),
    (18, G + "Gamemode/so_retro_v2.chr"),
    (19, G + "Level Sprites/bankportals.chr"),
    (20, G + "Gamemode/bankgamemodesA.chr"),
    (21, G + "Level Sprites/bankportals.chr"),
    (22, G + "Gamemode/bankgamemodesAretro.chr"),
    (23, G + "Level Sprites/bankportals.chr"),
    (24, G + "Gamemode/bankgamemodesB.chr"),
    (25, G + "Level Sprites/bankportals.chr"),
    (26, G + "Gamemode/bankgamemodesBretro.chr"),
    (27, G + "Level Sprites/bankportals.chr"),
    (28, G + "Level Sprites/bankmain.chr"),
    (29, G + "Level Sprites/bankblank.chr"),
    (30, G + "Level Sprites/bankmain.chr"),
    (31, G + "Level Sprites/bankblank2.chr"),
    (32, G + "Level Sprites/bankmain.chr"),
    (33, G + "Level Sprites/bankblankcloud.chr"),
    (34, G + "Level Sprites/bankmain.chr"),
    (35, G + "Level Sprites/bankblankcloud2.chr"),
    (36, G + "Level Sprites/bankmain.chr"),
    (37, G + "Level Sprites/bankblankfingerdash.chr"),
    (38, G + "Level Sprites/bankmain.chr"),
    (39, G + "Level Sprites/bankblankfingerdash2.chr"),
    # 40-67: fourteen icons, each followed by the portals bank.
    *[e for i in range(14) for e in (
        (40 + i * 2, G + "Icons/bankicon%02X.chr" % i),
        (41 + i * 2, G + "Level Sprites/bankportals.chr"))],
    (92, G + "Gamemode/banktriangle.chr"),
    (93, G + "Level Sprites/bankportals.chr"),
    (94, G + "Gamemode/bankfootball.chr"),
    (95, G + "Level Sprites/bankportals.chr"),
]

# The 2KB banks mmc3_set_2kb_chr_bank_0/1 can be called with in gameplay.
DEFAULT_BANKS = [18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 92, 94]


def build_1kb_banks(root: Path):
    """{bank number: 1KB of NES CHR} for everything GAMECHR names."""
    out = {}
    for bank, rel in GAMECHR:
        path = root / rel
        if not path.exists():
            sys.exit(f"{path} not found")
        data = path.read_bytes()
        for half in range(len(data) // 1024):
            out[bank + half] = data[half * 1024:(half + 1) * 1024]
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default="C:/famidash")
    ap.add_argument("--outdir", default=str(ROOT / "out"))
    ap.add_argument("--icons", type=int, default=1,
                    help="how many icon banks to include, from icon 0")
    args = ap.parse_args()
    outdir = Path(args.outdir)

    banks1k = build_1kb_banks(Path(args.root))

    wanted = sorted(set(DEFAULT_BANKS) | {40 + i * 2 for i in range(args.icons)})
    for b in wanted:
        if b not in banks1k or (b + 1) not in banks1k:
            sys.exit(f"2KB bank {b}: GAMECHR has no 1KB bank {b} or {b + 1}")

    asm = ["; Generated by tools/gen_sprchr.py - do not edit.",
           "; One 2KB NES sprite CHR bank per section, widened to SNES 4bpp:",
           "; 128 tiles, 4KB, DMA'd into OBJ VRAM when the game switches banks.",
           ""]
    for b in wanted:
        data = m.nes_chr_to_snes_4bpp(banks1k[b] + banks1k[b + 1])
        assert len(data) == 4096, len(data)
        (outdir / f"sprchr{b}.bin").write_bytes(data)
        # One shared section name so the linker lays them out in order from
        # the start of the SpriteCHR bank; 4KB divides 64KB, so no block can
        # straddle a bank and break its DMA.
        asm += [f"        .section sprchr,text,root",
                f"        .public spr_chr_bank{b}",
                f"spr_chr_bank{b}:",
                f'        .incbin "out/sprchr{b}.bin"', ""]
    (outdir / "spr_chr.s").write_text("\n".join(asm))

    externs = "\n".join(f"extern const uint8_t spr_chr_bank{b}[];" for b in wanted)
    nums = ", ".join(str(b) for b in wanted)
    ptrs = ", ".join(f"spr_chr_bank{b}" for b in wanted)
    (outdir / "spr_chr_meta.c").write_text(f"""\
/* Generated by tools/gen_sprchr.py - do not edit. */
#include <stdint.h>

{externs}

/* Parallel arrays rather than a 96-entry sparse table: the lookup runs once per
 * bank CHANGE, not per frame, and a linear scan of {len(wanted)} entries is
 * cheaper than the ROM a full table would cost. */
const uint8_t spr_chr_bank_count = {len(wanted)};
const uint8_t spr_chr_bank_num[{len(wanted)}] = {{ {nums} }};
const uint8_t *const spr_chr_bank_ptr[{len(wanted)}] = {{ {ptrs} }};
""")
    print(f"    spr_chr.s ({len(wanted)} sprite CHR banks, "
          f"{len(wanted) * 4}KB: {nums})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
